name: Run Geth Upgrade
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

env:
  GITHUB_USERNAME: ${{ secrets.QUORUM_BOT_GITHUB_USERNAME }}
  GITHUB_USER_TOKEN: ${{ secrets.QUORUM_BOT_GITHUB_USER_TOKEN }}
  GOPATH: /tmp
  
jobs:
  check_geth:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.15.5
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.5
        id: go
      - name: Git Show Version
        run: git version
      - name: Clone upgrade geth bot
        run: |
          git version
          git clone https://github.com/Consensys/quorum-bots.git $GOPATH/src/upgradebot
      - name: Execute upgrade geth bot
        run: |
          go version
          # go run upgradebot/cmd
